#!/usr/bin/env bash

wget -O /tmp/go-agent.deb http://download01.thoughtworks.com/go/13.4.1/ga/go-agent-13.4.1-18342.deb
dpkg -i /tmp/go-agent.deb
sed -r -i "s/^(GO_SERVER)=(.*)/\1=\$SERVER_PORT_8153_TCP_ADDR/g" /etc/default/go-agent
