#!/usr/bin/env bash

echo "deb http://archive.ubuntu.com/ubuntu precise universe" >> /etc/apt/sources.list
apt-get install -y software-properties-common
add-apt-repository -y ppa:chris-lea/node.js
apt-get update
apt-get install -y nodejs
echo '\n# Node.js\nexport PATH="node_modules/.bin:$PATH"' >> /root/.bash_profile
